-- AA Tuition v10.16.1 — OCR A A-level Chemistry (H432)
-- Curriculum order follows the textbook contents supplied by the tutor.
-- Modules 1–4 = Year 1 / AS content; Modules 5–6 = Year 2 content.
-- Safe to run more than once: existing A-level Chemistry curriculum rows are replaced.

delete from public.curriculum_topics
where course = 'A-level Chemistry';

insert into public.curriculum_topics
  (course, module, chapter_number, chapter_name, topic_number, topic_name, position, higher_only)
values
('A-level Chemistry','Module 1 – Development of practical skills in chemistry','1','Development of practical skills in chemistry','1','Development of practical skills in chemistry',1,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','2','Atoms, ions, and compounds','2.1','Atomic structure and isotopes',2,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','2','Atoms, ions, and compounds','2.2','Relative mass',3,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','2','Atoms, ions, and compounds','2.3','Formulae and equations',4,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','3','Amount of substance','3.1','Amount of substance and the mole',5,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','3','Amount of substance','3.2','Determination of formulae',6,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','3','Amount of substance','3.3','Moles and volumes',7,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','3','Amount of substance','3.4','Reacting quantities',8,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','4','Acids and redox','4.1','Acids, bases, and neutralisation',9,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','4','Acids and redox','4.2','Acid–base titrations',10,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','4','Acids and redox','4.3','Redox',11,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','5','Electrons and bonding','5.1','Electron structure',12,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','5','Electrons and bonding','5.2','Ionic bonding and structure',13,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','5','Electrons and bonding','5.3','Covalent bonding',14,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','6','Shapes of molecules and intermolecular forces','6.1','Shapes of molecules and ions',15,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','6','Shapes of molecules and intermolecular forces','6.2','Electronegativity and polarity',16,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','6','Shapes of molecules and intermolecular forces','6.3','Intermolecular forces',17,false),
('A-level Chemistry','Module 2 – Foundations in chemistry','6','Shapes of molecules and intermolecular forces','6.4','Hydrogen bonding',18,false),
('A-level Chemistry','Module 3 – Periodic table and energy','7','Periodicity','7.1','The periodic table',19,false),
('A-level Chemistry','Module 3 – Periodic table and energy','7','Periodicity','7.2','Ionisation energies',20,false),
('A-level Chemistry','Module 3 – Periodic table and energy','7','Periodicity','7.3','Periodic trends in bonding and structure',21,false),
('A-level Chemistry','Module 3 – Periodic table and energy','8','Reactivity trends','8.1','Group 2',22,false),
('A-level Chemistry','Module 3 – Periodic table and energy','8','Reactivity trends','8.2','The halogens',23,false),
('A-level Chemistry','Module 3 – Periodic table and energy','8','Reactivity trends','8.3','Qualitative analysis',24,false),
('A-level Chemistry','Module 3 – Periodic table and energy','9','Enthalpy','9.1','Enthalpy changes',25,false),
('A-level Chemistry','Module 3 – Periodic table and energy','9','Enthalpy','9.2','Measuring enthalpy changes',26,false),
('A-level Chemistry','Module 3 – Periodic table and energy','9','Enthalpy','9.3','Bond enthalpies',27,false),
('A-level Chemistry','Module 3 – Periodic table and energy','9','Enthalpy','9.4','Hess'' law and enthalpy cycles',28,false),
('A-level Chemistry','Module 3 – Periodic table and energy','10','Reaction rates and equilibrium','10.1','Reaction rates',29,false),
('A-level Chemistry','Module 3 – Periodic table and energy','10','Reaction rates and equilibrium','10.2','Catalysts',30,false),
('A-level Chemistry','Module 3 – Periodic table and energy','10','Reaction rates and equilibrium','10.3','The Boltzmann distribution',31,false),
('A-level Chemistry','Module 3 – Periodic table and energy','10','Reaction rates and equilibrium','10.4','Dynamic equilibrium and Le Chatelier''s principle',32,false),
('A-level Chemistry','Module 3 – Periodic table and energy','10','Reaction rates and equilibrium','10.5','The equilibrium constant Kc – part 1',33,false),
('A-level Chemistry','Module 4 – Core organic chemistry','11','Basic concepts of organic chemistry','11.1','Organic chemistry',34,false),
('A-level Chemistry','Module 4 – Core organic chemistry','11','Basic concepts of organic chemistry','11.2','Nomenclature of organic compounds',35,false),
('A-level Chemistry','Module 4 – Core organic chemistry','11','Basic concepts of organic chemistry','11.3','Representing the formulae of organic compounds',36,false),
('A-level Chemistry','Module 4 – Core organic chemistry','11','Basic concepts of organic chemistry','11.4','Isomerism',37,false),
('A-level Chemistry','Module 4 – Core organic chemistry','11','Basic concepts of organic chemistry','11.5','Introduction to reaction mechanisms',38,false),
('A-level Chemistry','Module 4 – Core organic chemistry','12','Alkanes','12.1','Properties of alkanes',39,false),
('A-level Chemistry','Module 4 – Core organic chemistry','12','Alkanes','12.2','Chemical reactions of alkanes',40,false),
('A-level Chemistry','Module 4 – Core organic chemistry','13','Alkenes','13.1','Properties of alkenes',41,false),
('A-level Chemistry','Module 4 – Core organic chemistry','13','Alkenes','13.2','Stereoisomerism',42,false),
('A-level Chemistry','Module 4 – Core organic chemistry','13','Alkenes','13.3','Reactions of alkenes',43,false),
('A-level Chemistry','Module 4 – Core organic chemistry','13','Alkenes','13.4','Electrophilic addition in alkenes',44,false),
('A-level Chemistry','Module 4 – Core organic chemistry','13','Alkenes','13.5','Polymerisation in alkenes',45,false),
('A-level Chemistry','Module 4 – Core organic chemistry','14','Alcohols','14.1','Properties of alcohols',46,false),
('A-level Chemistry','Module 4 – Core organic chemistry','14','Alcohols','14.2','Reactions of alcohols',47,false),
('A-level Chemistry','Module 4 – Core organic chemistry','15','Haloalkanes','15.1','The chemistry of the haloalkanes',48,false),
('A-level Chemistry','Module 4 – Core organic chemistry','15','Haloalkanes','15.2','Organohalogen compounds in the environment',49,false),
('A-level Chemistry','Module 4 – Core organic chemistry','16','Organic synthesis','16.1','Practical techniques in organic chemistry',50,false),
('A-level Chemistry','Module 4 – Core organic chemistry','16','Organic synthesis','16.2','Synthetic routes',51,false),
('A-level Chemistry','Module 4 – Core organic chemistry','17','Spectroscopy','17.1','Mass spectrometry',52,false),
('A-level Chemistry','Module 4 – Core organic chemistry','17','Spectroscopy','17.2','Infrared spectroscopy',53,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','18','Rates of reactions','18.1','Orders, rate equations, and rate constants',54,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','18','Rates of reactions','18.2','Concentration–time graphs',55,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','18','Rates of reactions','18.3','Rate–concentration graphs',56,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','18','Rates of reactions','18.4','Rate-determining step',57,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','18','Rates of reactions','18.5','Rate constants and temperature',58,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','19','Equilibrium','19.1','The equilibrium constant Kc – part 2',59,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','19','Equilibrium','19.2','The equilibrium constant Kp',60,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','19','Equilibrium','19.3','Controlling the position of equilibrium',61,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','20','Acids, bases, and pH','20.1','Brønsted–Lowry acids and bases',62,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','20','Acids, bases, and pH','20.2','The pH scale and strong acids',63,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','20','Acids, bases, and pH','20.3','The acid dissociation constant Ka',64,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','20','Acids, bases, and pH','20.4','The pH of weak acids',65,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','20','Acids, bases, and pH','20.5','pH and strong bases',66,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','21','Buffers and neutralisation','21.1','Buffer solutions',67,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','21','Buffers and neutralisation','21.2','Buffer solutions in the body',68,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','21','Buffers and neutralisation','21.3','Neutralisation',69,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','22','Enthalpy and entropy','22.1','Lattice enthalpy',70,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','22','Enthalpy and entropy','22.2','Enthalpy changes in solution',71,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','22','Enthalpy and entropy','22.3','Factors affecting lattice enthalpy and hydration',72,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','22','Enthalpy and entropy','22.4','Entropy',73,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','22','Enthalpy and entropy','22.5','Free energy',74,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','23','Redox and electrode potentials','23.1','Redox reactions',75,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','23','Redox and electrode potentials','23.2','Manganate(VII) redox titrations',76,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','23','Redox and electrode potentials','23.3','Iodine/thiosulfate redox titrations',77,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','23','Redox and electrode potentials','23.4','Electrode potentials',78,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','23','Redox and electrode potentials','23.5','Predictions from electrode potentials',79,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','23','Redox and electrode potentials','23.6','Storage and fuel cells',80,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','24','Transition elements','24.1','d-block elements',81,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','24','Transition elements','24.2','The formation and shapes of complex ions',82,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','24','Transition elements','24.3','Stereoisomerism in complex ions',83,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','24','Transition elements','24.4','Ligand substitution and precipitation',84,false),
('A-level Chemistry','Module 5 – Physical chemistry and transition elements','24','Transition elements','24.5','Redox and qualitative analysis',85,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','25','Aromatic chemistry','25.1','Introducing benzene',86,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','25','Aromatic chemistry','25.2','Electrophilic substitution reactions of benzene',87,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','25','Aromatic chemistry','25.3','The chemistry of phenol',88,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','25','Aromatic chemistry','25.4','Disubstitution and directing groups',89,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','26','Carbonyls and carboxylic acids','26.1','Carbonyl compounds',90,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','26','Carbonyls and carboxylic acids','26.2','Identifying aldehydes and ketones',91,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','26','Carbonyls and carboxylic acids','26.3','Carboxylic acids',92,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','26','Carbonyls and carboxylic acids','26.4','Carboxylic acid derivatives',93,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','27','Amines, amino acids, and proteins','27.1','Amines',94,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','27','Amines, amino acids, and proteins','27.2','Amino acids, amides, and chirality',95,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','27','Amines, amino acids, and proteins','27.3','Condensation polymers',96,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','28','Organic synthesis','28.1','Carbon–carbon bond formation',97,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','28','Organic synthesis','28.2','Further practical techniques',98,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','28','Organic synthesis','28.3','Further synthetic routes',99,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','29','Chromatography and spectroscopy','29.1','Chromatography and functional group analysis',100,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','29','Chromatography and spectroscopy','29.2','Nuclear magnetic resonance (NMR) spectroscopy',101,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','29','Chromatography and spectroscopy','29.3','Carbon-13 NMR spectroscopy',102,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','29','Chromatography and spectroscopy','29.4','Proton NMR spectroscopy',103,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','29','Chromatography and spectroscopy','29.5','Interpreting NMR spectra',104,false),
('A-level Chemistry','Module 6 – Organic chemistry and analysis','29','Chromatography and spectroscopy','29.6','Combined techniques',105,false);
