-- AA Tuition v7: rate-limit support for the server-side student access-code endpoint.
-- Safe additive migration: does not change or delete existing student data.

alter table public.students
add column if not exists access_code text;

alter table public.students
add column if not exists access_code_active boolean not null default true;

create unique index if not exists students_access_code_unique
on public.students (access_code)
where access_code is not null;

create table if not exists public.portal_access_attempts (
  id bigint generated by default as identity primary key,
  identifier text not null,
  attempted_at timestamptz not null default now()
);

create index if not exists portal_access_attempts_identifier_time_idx
on public.portal_access_attempts (identifier, attempted_at desc);

alter table public.portal_access_attempts enable row level security;

-- No anon/authenticated policies are intentionally created. The browser cannot
-- read or write this table; only the server-side service role uses it.
revoke all on table public.portal_access_attempts from anon, authenticated;
