import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
export default function Lessons(){
 const [students,setStudents]=useState([]),[courses,setCourses]=useState([]),[lessons,setLessons]=useState([]),[open,setOpen]=useState(false),[editingId,setEditingId]=useState(null),[error,setError]=useState(''),[studentFilter,setStudentFilter]=useState(''),[courseFilter,setCourseFilter]=useState('')
 const blank={student_id:'',student_course_id:'',lesson_date:new Date().toISOString().slice(0,10),topic:'',attendance:'present',duration_minutes:60,notes:'',homework:''}
 const [form,setForm]=useState(blank)
 const load=async()=>{const [{data:s},{data:c,error:ce},{data:l,error:e}]=await Promise.all([supabase.from('students').select('id,name').eq('active',true).order('name'),supabase.from('student_courses').select('id,student_id,course,exam_board,tier').order('created_at'),supabase.from('lessons').select('*').order('lesson_date',{ascending:false})]);setStudents(s||[]);setCourses(c||[]);setLessons(l||[]);if(e||ce)setError((e||ce).message)}
 useEffect(()=>{load()},[])
 const name=id=>students.find(s=>s.id===id)?.name||'Student'
 const course=id=>courses.find(c=>c.id===id)||null
 const studentCourses=studentId=>courses.filter(c=>c.student_id===studentId)
 const filtered=useMemo(()=>lessons.filter(l=>(!studentFilter||l.student_id===studentFilter)&&(!courseFilter||l.student_course_id===courseFilter)),[lessons,studentFilter,courseFilter])
 const chooseStudent=value=>{const available=studentCourses(value);setForm({...form,student_id:value,student_course_id:available[0]?.id||''})}
 const openNewLesson=()=>{setEditingId(null);setForm(blank);setOpen(true)}
 const editLesson=lesson=>{setEditingId(lesson.id);setForm({student_id:lesson.student_id,student_course_id:lesson.student_course_id||'',lesson_date:lesson.lesson_date,topic:lesson.topic||'',attendance:lesson.attendance||'present',duration_minutes:lesson.duration_minutes||60,notes:lesson.notes||'',homework:lesson.homework||''});setOpen(true)}
 const submit=async e=>{e.preventDefault();const payload={...form,student_course_id:form.student_course_id||null,duration_minutes:Number(form.duration_minutes||60)};const query=editingId?supabase.from('lessons').update(payload).eq('id',editingId):supabase.from('lessons').insert(payload);const {error}=await query;if(error){setError(error.message);return}setOpen(false);setEditingId(null);setForm(blank);load()}
 const deleteLesson=async lesson=>{if(!window.confirm(`Delete ${name(lesson.student_id)}'s lesson \"${lesson.topic}\" from ${lesson.lesson_date}? This cannot be undone.`))return;setError('');const {error}=await supabase.from('lessons').delete().eq('id',lesson.id);if(error)setError(error.message);else load()}
 return <><div className="pageHead"><div><span className="eyebrow">LESSONS</span><h1>Lesson log</h1><p className="pageIntro">Master history of lessons across all students. Individual student profiles show only their own lesson history.</p></div><button className="primary btn" onClick={openNewLesson}>+ Record lesson</button></div>{error&&<div className="errorBox">{error}</div>}<section className="panel"><div className="lessonLogFilters"><label>Student<select value={studentFilter} onChange={e=>{setStudentFilter(e.target.value);setCourseFilter('')}}><option value="">All students</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Course<select value={courseFilter} onChange={e=>setCourseFilter(e.target.value)}><option value="">All courses</option>{(studentFilter?studentCourses(studentFilter):courses).map(c=><option key={c.id} value={c.id}>{name(c.student_id)} · {c.course}</option>)}</select></label></div>{filtered.length?<><div className="tableWrap desktopOnly"><table><thead><tr><th>Date</th><th>Student</th><th>Course</th><th>Topic</th><th>Attendance</th><th>Duration</th><th>Notes</th><th>Homework</th><th></th></tr></thead><tbody>{filtered.map(l=>{const c=course(l.student_course_id);return <tr key={l.id}><td>{l.lesson_date}</td><td><b>{name(l.student_id)}</b></td><td>{c?.course||'—'}</td><td>{l.topic}</td><td><span className={`badge ${l.attendance==='present'?'green':l.attendance==='absent'?'red':'amber'}`}>{l.attendance}</span></td><td>{l.duration_minutes||60} mins</td><td className="notesCell">{l.notes||'—'}</td><td className="notesCell homeworkCell">{l.homework||'—'}</td><td><div className="lessonCardActions"><button type="button" className="textButton" onClick={()=>editLesson(l)}>Edit</button><button type="button" className="textButton dangerText" onClick={()=>deleteLesson(l)}>Delete</button></div></td></tr>})}</tbody></table></div><div className="lessonCardList mobileOnly">{filtered.map(l=>{const c=course(l.student_course_id);return <article className="lessonMobileCard" key={l.id}><div className="lessonMobileTop"><div><b>{name(l.student_id)}</b><span>{l.lesson_date}{c?.course?` · ${c.course}`:''}</span></div><span className={`badge ${l.attendance==='present'?'green':l.attendance==='absent'?'red':'amber'}`}>{l.attendance}</span></div><h3>{l.topic}</h3><div className="lessonMeta">{l.duration_minutes||60} mins</div>{l.notes&&<div className="lessonBlock"><span>Lesson notes</span><p>{l.notes}</p></div>}{l.homework&&<div className="lessonBlock homework"><span>Homework</span><p>{l.homework}</p></div>}<div className="lessonCardActions"><button type="button" className="textButton" onClick={()=>editLesson(l)}>Edit</button><button type="button" className="textButton dangerText" onClick={()=>deleteLesson(l)}>Delete lesson</button></div></article>})}</div></>:<div className="empty">No lessons match these filters.</div>}</section>
 {open&&<div className="modalBackdrop" onMouseDown={()=>setOpen(false)}><div className="modalCard" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><h2>{editingId?'Edit lesson':'Record lesson'}</h2><button className="ghost" onClick={()=>{setOpen(false);setEditingId(null);setForm(blank)}}>Close</button></div><form className="formGrid" onSubmit={submit}><label>Student<select required value={form.student_id} onChange={e=>chooseStudent(e.target.value)}><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Date<input type="date" value={form.lesson_date} onChange={e=>setForm({...form,lesson_date:e.target.value})}/></label>{form.student_id&&studentCourses(form.student_id).length>0&&<label className="full">Course<select required value={form.student_course_id} onChange={e=>setForm({...form,student_course_id:e.target.value})}>{studentCourses(form.student_id).map(c=><option key={c.id} value={c.id}>{c.course}{c.exam_board?` · ${c.exam_board}`:''}{c.tier?` · ${c.tier}`:''}</option>)}</select></label>}<label>Topic<input required value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})}/></label><label>Attendance<select value={form.attendance} onChange={e=>setForm({...form,attendance:e.target.value})}><option value="present">Present</option><option value="absent">Absent</option><option value="cancelled">Cancelled</option></select></label><label>Duration (minutes)<input type="number" value={form.duration_minutes} onChange={e=>setForm({...form,duration_minutes:e.target.value})}/></label><label className="full">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label className="full">Homework<textarea value={form.homework} onChange={e=>setForm({...form,homework:e.target.value})}/></label><div className="full"><button className="primary">{editingId?'Save changes':'Save lesson'}</button></div></form></div></div>}
 </>
}
