import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
export default function Lessons(){
 const [students,setStudents]=useState([]),[lessons,setLessons]=useState([]),[open,setOpen]=useState(false),[error,setError]=useState('')
 const [form,setForm]=useState({student_id:'',lesson_date:new Date().toISOString().slice(0,10),topic:'',attendance:'present',duration_minutes:60,notes:'',homework:''})
 const load=async()=>{const [{data:s},{data:l,error:e}]=await Promise.all([supabase.from('students').select('id,name').eq('active',true).order('name'),supabase.from('lessons').select('*').order('lesson_date',{ascending:false})]);setStudents(s||[]);setLessons(l||[]);if(e)setError(e.message)}
 useEffect(()=>{load()},[])
 const name=id=>students.find(s=>s.id===id)?.name||'Student'
 const submit=async e=>{e.preventDefault();const {error}=await supabase.from('lessons').insert({...form,duration_minutes:Number(form.duration_minutes||60)});if(error){setError(error.message);return}setOpen(false);setForm({...form,student_id:'',topic:'',notes:'',homework:''});load()}
 return <><div className="pageHead"><div><span className="eyebrow">LESSONS</span><h1>Lesson log</h1></div><button className="primary btn" onClick={()=>setOpen(true)}>+ Record lesson</button></div>{error&&<div className="errorBox">{error}</div>}<section className="panel">{lessons.length?<><div className="tableWrap desktopOnly"><table><thead><tr><th>Date</th><th>Student</th><th>Topic</th><th>Attendance</th><th>Duration</th><th>Notes</th><th>Homework</th></tr></thead><tbody>{lessons.map(l=><tr key={l.id}><td>{l.lesson_date}</td><td><b>{name(l.student_id)}</b></td><td>{l.topic}</td><td><span className={`badge ${l.attendance==='present'?'green':l.attendance==='absent'?'red':'amber'}`}>{l.attendance}</span></td><td>{l.duration_minutes||60} mins</td><td className="notesCell">{l.notes||'—'}</td><td className="notesCell homeworkCell">{l.homework||'—'}</td></tr>)}</tbody></table></div><div className="lessonCardList mobileOnly">{lessons.map(l=><article className="lessonMobileCard" key={l.id}><div className="lessonMobileTop"><div><b>{name(l.student_id)}</b><span>{l.lesson_date}</span></div><span className={`badge ${l.attendance==='present'?'green':l.attendance==='absent'?'red':'amber'}`}>{l.attendance}</span></div><h3>{l.topic}</h3><div className="lessonMeta">{l.duration_minutes||60} mins</div>{l.notes&&<div className="lessonBlock"><span>Lesson notes</span><p>{l.notes}</p></div>}{l.homework&&<div className="lessonBlock homework"><span>Homework</span><p>{l.homework}</p></div>}</article>)}</div></>:<div className="empty">No lessons recorded yet.</div>}</section>
 {open&&<div className="modalBackdrop" onMouseDown={()=>setOpen(false)}><div className="modalCard" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><h2>Record lesson</h2><button className="ghost" onClick={()=>setOpen(false)}>Close</button></div><form className="formGrid" onSubmit={submit}><label>Student<select required value={form.student_id} onChange={e=>setForm({...form,student_id:e.target.value})}><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Date<input type="date" value={form.lesson_date} onChange={e=>setForm({...form,lesson_date:e.target.value})}/></label><label>Topic<input required value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})}/></label><label>Attendance<select value={form.attendance} onChange={e=>setForm({...form,attendance:e.target.value})}><option>present</option><option>absent</option><option>cancelled</option></select></label><label>Duration (minutes)<input type="number" value={form.duration_minutes} onChange={e=>setForm({...form,duration_minutes:e.target.value})}/></label><label className="full">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label className="full">Homework<textarea value={form.homework} onChange={e=>setForm({...form,homework:e.target.value})}/></label><div className="full"><button className="primary">Save lesson</button></div></form></div></div>}
 </>
}
