import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import StatusBadge from '../components/StatusBadge'
import { progressSnapshot } from '../lib/gcseCurriculum'
import { useAuth } from '../context/AuthContext'
import { COURSE_OPTIONS, EXAM_BOARDS, FURTHER_CORE, FURTHER_OPTIONAL, blankCourseSettings, isFurtherCourse, isGcseCourse } from '../lib/courseData'

const blank={name:'',tutor_update:''}
export default function Students(){
  const {user}=useAuth()
  const [students,setStudents]=useState([]),[profiles,setProfiles]=useState([]),[courses,setCourses]=useState([]),[courseModules,setCourseModules]=useState([]),[curriculumRows,setCurriculumRows]=useState([]),[lessons,setLessons]=useState([]),[topics,setTopics]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[error,setError]=useState(''),[form,setForm]=useState(blank),[selectedCourses,setSelectedCourses]=useState(['GCSE Mathematics']),[courseSettings,setCourseSettings]=useState({'GCSE Mathematics':blankCourseSettings('GCSE Mathematics')})
  const load=async()=>{setLoading(true);const [{data:s,error:se},{data:p,error:pe},{data:c,error:ce},{data:l,error:le},{data:t,error:te},{data:cr,error:cre}]=await Promise.all([supabase.from('students').select('*').eq('active',true).order('name'),supabase.from('profiles').select('id,full_name,role').in('role',['owner','tutor']).order('full_name'),supabase.from('student_courses').select('*').order('created_at'),supabase.from('lessons').select('student_id,attendance'),supabase.from('topic_progress').select('student_id,student_course_id,curriculum_topic_id,topic,status'),supabase.from('curriculum_topics').select('*').in('course',['GCSE Combined Science','A-level Mathematics','A-level Further Mathematics','A-level Chemistry']).order('position')]);let cm=[];if(c?.length){const {data,error}=await supabase.from('student_course_modules').select('*').in('student_course_id',c.map(x=>x.id));if(error)setError(error.message);else cm=data||[]}if(se||pe||ce||le||te||cre)setError((se||pe||ce||le||te||cre)?.message||'Could not load students');setStudents(s||[]);setProfiles(p||[]);setCourses(c||[]);setCourseModules(cm);setCurriculumRows(cr||[]);setLessons(l||[]);setTopics(t||[]);setLoading(false)}
  useEffect(()=>{load()},[])
  const attendance=useMemo(()=>Object.fromEntries(students.map(s=>{const ls=lessons.filter(l=>l.student_id===s.id&&l.attendance!=='cancelled');const present=ls.filter(l=>l.attendance==='present').length;return[s.id,ls.length?Math.round(present/ls.length*100):null]})),[students,lessons])
  const rows=useMemo(()=>students.map(s=>{const studentCourses=courses.filter(c=>c.student_id===s.id);const primary=studentCourses[0];const modules=primary?courseModules.filter(m=>m.student_course_id===primary.id).map(m=>m.module):[];const display=primary?{...s,...primary,id:s.id,curriculum_modules:modules,curriculum_rows:curriculumRows.filter(r=>r.course===primary.course)}:s;return {...progressSnapshot(display,topics.filter(t=>t.student_id===s.id&&(!primary||t.student_course_id===primary.id))),attendance:attendance[s.id],studentCourses}}),[students,courses,courseModules,curriculumRows,topics,attendance])
  const makeCode=()=>`AA${String(Math.floor(Math.random()*10000)).padStart(4,'0')}`
  const reset=()=>{setForm(blank);setSelectedCourses(['GCSE Mathematics']);setCourseSettings({'GCSE Mathematics':{...blankCourseSettings('GCSE Mathematics'),tutor_id:user?.id||''}})}
  const toggleCourse=course=>{setSelectedCourses(current=>{if(current.includes(course))return current.filter(x=>x!==course);setCourseSettings(v=>({...v,[course]:v[course]||{...blankCourseSettings(course),tutor_id:user?.id||''}}));return [...current,course]})}
  const updateCourse=(course,patch)=>setCourseSettings(v=>({...v,[course]:{...(v[course]||blankCourseSettings(course)),...patch}}))
  const submit=async e=>{e.preventDefault();setError('');if(!selectedCourses.length){setError('Select at least one course.');return}for(const course of selectedCourses){const c=courseSettings[course]||blankCourseSettings(course);if(isFurtherCourse(c)){const optional=(c.modules||[]).filter(m=>FURTHER_OPTIONAL.includes(m));if(optional.length!==2){setError('For A-level Further Mathematics, choose exactly two optional textbooks. Core Pure 1 and Core Pure 2 are included automatically.');return}}}
    const primary=courseSettings[selectedCourses[0]]||blankCourseSettings(selectedCourses[0]);const base={name:form.name,course:primary.course,target_grade:primary.target_grade||null,working_grade:primary.working_grade||null,tutor_update:form.tutor_update||null,exam_board:primary.exam_board||null,tier:isGcseCourse(primary)?primary.tier||null:null,baseline_progress:primary.baseline_progress===''?null:Number(primary.baseline_progress),progress_start_date:primary.progress_start_date||null,target_date:primary.target_date||null,access_code_active:true};let student=null,lastError=null;for(let attempt=0;attempt<12;attempt++){const {data,error}=await supabase.from('students').insert({...base,access_code:makeCode()}).select().single();if(!error){student=data;break}lastError=error;if(error.code!=='23505'||!String(error.message||'').includes('access_code'))break}if(!student){setError(lastError?.message||'Could not create student.');return}
    const courseRows=selectedCourses.map(course=>{const c=courseSettings[course]||blankCourseSettings(course);return {student_id:student.id,course,exam_board:c.exam_board||null,tier:isGcseCourse(c)?c.tier||null:null,target_grade:c.target_grade||null,working_grade:c.working_grade||null,baseline_progress:c.baseline_progress===''?null:Number(c.baseline_progress),progress_start_date:c.progress_start_date||null,target_date:c.target_date||null}})
    const {data:created,error:courseError}=await supabase.from('student_courses').insert(courseRows).select();if(courseError){await supabase.from('students').delete().eq('id',student.id);setError(courseError.message);return}
    const moduleRows=[];(created||[]).forEach(c=>{if(c.course==='A-level Further Mathematics'){const settings=courseSettings[c.course];[...FURTHER_CORE,...settings.modules.filter(m=>FURTHER_OPTIONAL.includes(m))].forEach(module=>moduleRows.push({student_course_id:c.id,module}))}});if(moduleRows.length){const {error:moduleError}=await supabase.from('student_course_modules').insert(moduleRows);if(moduleError){setError(moduleError.message);return}}
    const courseTutorRows=(created||[]).map(c=>({student_course_id:c.id,tutor_id:(courseSettings[c.course]?.tutor_id||user?.id||'')}));if(courseTutorRows.some(x=>!x.tutor_id)){await supabase.from('students').delete().eq('id',student.id);setError('Choose a tutor for every course.');return}if(courseTutorRows.length){const {error:tutorCourseError}=await supabase.from('student_course_tutors').insert(courseTutorRows);if(tutorCourseError){await supabase.from('students').delete().eq('id',student.id);setError('Courses could not be assigned to tutors: '+tutorCourseError.message);return}const legacyLinks=[...new Set(courseTutorRows.map(x=>x.tutor_id))].map(tutor_id=>({student_id:student.id,tutor_id}));const {error:tutorLinkError}=await supabase.from('student_tutors').insert(legacyLinks);if(tutorLinkError){await supabase.from('students').delete().eq('id',student.id);setError('Student could not be assigned to tutors: '+tutorLinkError.message);return}}
    setOpen(false);reset();load()
  }
  if(loading)return <div className="loading">Loading students…</div>
  return <><div className="pageHead"><div><span className="eyebrow">STUDENTS</span><h1>Student directory</h1><p>Open a profile to update progress, assessments, topics and tutor notes.</p></div><button className="primary btn" onClick={()=>setOpen(true)}>+ Add student</button></div>{error&&<div className="errorBox">{error}</div>}<section className="panel">{rows.length?<><div className="tableWrap desktopOnly"><table><thead><tr><th>Student</th><th>Course</th><th>Attendance</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><b>{s.name}</b></td><td>{s.studentCourses.length?s.studentCourses.map(c=>c.course).join(' · '):s.course}</td><td>{s.attendance==null?'—':`${s.attendance}%`}</td><td>{s.expectedConfigured?<StatusBadge student={s}/>:<span className="badge neutral">Set timeline</span>}</td><td><Link className="textLink" to={`/students/${s.id}`}>Open profile →</Link></td></tr>)}</tbody></table></div><div className="studentDirectoryCards mobileOnly">{rows.map(s=><Link className="directoryCard" key={s.id} to={`/students/${s.id}`}><div className="directoryTop"><div><b>{s.name}</b><span>{s.studentCourses.length?s.studentCourses.map(c=>c.course).join(' · '):s.course}</span></div>{s.expectedConfigured?<StatusBadge student={s}/>:<span className="badge neutral">Set timeline</span>}</div><div className="directoryMetrics"><span>Attendance <b>{s.attendance==null?'—':`${s.attendance}%`}</b></span></div><div className="textLink">Open profile →</div></Link>)}</div></>:<div className="empty">No students yet. Tap “Add student” to create your first record.</div>}</section>
  {open&&<div className="modalBackdrop" onMouseDown={()=>setOpen(false)}><div className="modalCard wideModal" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><span className="eyebrow">NEW STUDENT</span><h2>Add student</h2></div><button className="ghost" onClick={()=>setOpen(false)}>Close</button></div><form className="formGrid" onSubmit={submit}><label className="full">Student name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="full coursePicker"><span className="formSectionLabel">Courses</span><p className="fieldHelp">Select every course this student takes. A student can take multiple courses, and each course can have its own tutor.</p><div className="courseChoiceGrid">{COURSE_OPTIONS.map(course=><label className={`courseChoice ${selectedCourses.includes(course)?'selected':''}`} key={course}><input type="checkbox" checked={selectedCourses.includes(course)} onChange={()=>toggleCourse(course)}/><span>{course}</span></label>)}</div></div>{selectedCourses.map(course=><CourseSettings key={course} course={course} value={courseSettings[course]||blankCourseSettings(course)} onChange={patch=>updateCourse(course,patch)} tutorProfiles={profiles} userId={user?.id}/>)}<label className="full">Tutor update<textarea value={form.tutor_update} onChange={e=>setForm({...form,tutor_update:e.target.value})} placeholder="Strengths, areas to improve and next steps"/></label><div className="full"><button className="primary">Save student</button></div></form></div></div>}</>
}

function CourseSettings({course,value,onChange,tutorProfiles=[],userId}){const optional=(value.modules||[]).filter(m=>FURTHER_OPTIONAL.includes(m));return <div className="full courseSettingsCard"><div className="courseSettingsHead"><div><span className="eyebrow">COURSE</span><h3>{course}</h3></div>{isFurtherCourse(value)&&<span className="moduleCounter">{optional.length}/2 optional books</span>}</div><div className="formGrid"><label className="full">Assigned tutor<select required value={value.tutor_id||userId||''} onChange={e=>onChange({tutor_id:e.target.value})}><option value="">Choose tutor</option>{tutorProfiles.map(p=><option key={p.id} value={p.id}>{p.id===userId?`${p.full_name} (You)`:p.full_name}</option>)}</select><small className="fieldHelp">Tutor assignment applies to this course only.</small></label><label>Exam board<select value={value.exam_board||''} onChange={e=>onChange({exam_board:e.target.value})}><option value="">Not set</option>{EXAM_BOARDS.map(x=><option key={x}>{x}</option>)}</select></label>{isGcseCourse(value)&&<label>Tier<select value={value.tier||''} onChange={e=>onChange({tier:e.target.value})}><option value="">Not set</option><option>Foundation</option><option>Higher</option></select></label>}<label>Target grade<input value={value.target_grade||''} onChange={e=>onChange({target_grade:e.target.value})}/></label><label>Working grade<input value={value.working_grade||''} onChange={e=>onChange({working_grade:e.target.value})}/></label><label>Baseline progress %<input type="number" min="0" max="100" value={value.baseline_progress??''} onChange={e=>onChange({baseline_progress:e.target.value})}/></label><label>Tracking start date<input type="date" value={value.progress_start_date||''} onChange={e=>onChange({progress_start_date:e.target.value})}/></label><label>Target completion date<input type="date" value={value.target_date||''} onChange={e=>onChange({target_date:e.target.value})}/></label>{isFurtherCourse(value)&&<div className="full curriculumModuleEditor"><span className="formSectionLabel">Further Maths textbooks</span><p className="fieldHelp"><b>Core Pure 1</b> and <b>Core Pure 2</b> are compulsory. Choose exactly two optional textbooks.</p><div className="compulsoryModules"><span>✓ Core Pure 1</span><span>✓ Core Pure 2</span></div><div className="moduleChecks">{FURTHER_OPTIONAL.map(m=><label className="moduleCheck" key={m}><input type="checkbox" checked={optional.includes(m)} onChange={e=>{let next=optional;if(e.target.checked){if(optional.length>=2)return;next=[...optional,m]}else next=optional.filter(x=>x!==m);onChange({modules:[...FURTHER_CORE,...next]})}}/><span>{m}</span></label>)}</div></div>}</div></div>}
